-- Rawli Analytics waitlist table
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz default now()
);

-- Enable RLS (service role bypasses)
alter table public.waitlist enable row level security;

-- Optional: enforce lowercase emails
create or replace function public.normalize_waitlist_email()
returns trigger
language plpgsql
as $$
begin
  new.email := lower(trim(new.email));
  return new;
end;
$$;

create or replace trigger normalize_waitlist_email
before insert or update on public.waitlist
for each row
execute function public.normalize_waitlist_email();

-- Security: lock down function search_path
alter function public.normalize_waitlist_email()
set search_path = public;
